name: Jekyll Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create /docs directory if it doesn't exist
      run: mkdir -p ${{ github.workspace }}/docs

    - name: Build Jekyll site
      run: |
        # Your build commands here
